version: '3.8'

services:
  web:
    build: .
    container_name: beeteller-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: beeteller-db
    restart: always
    environment:
      POSTGRES_USER: beeteller
      POSTGRES_PASSWORD: beeteller
      POSTGRES_DB: pix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
